### ISSUE TITLE
Не работает параллакс на htc android 2.3

### ISSUE THREAD

**Issue by Sashafmp** [affshate/alina_pozdravlyaem_tebya_s_dnem_rozhdeniya_tvoi_lubimie_kollegi#1]

**Comment by trymoto** [comment]
Hello, @Sashafmp !
Thanks for reporting this.
Unfortunately, we no longer maintain this project, so if it bugs you any PR is welcome.
![rs_600x600-170211120220-600 kanye-west cm 21117](https://user-images.githubusercontent.com/2513899/28715807-65935288-73a2-11e7-8e49-64877157b0f5.jpg)
